### ISSUE TITLE
finetune了模型后，在infer时报错，IndexError

### ISSUE THREAD

**Issue by yuanshengjun** [bojone/t5_in_bert4keras#9]
一、finetune存储的模型如下：
t5.save_weights_as_checkpoint("best_model_mt5/best_model.ckpt" )

二、infer时，加载模型如下：
fine_tune_checkpoint_path = 'best_model_mt5/best_model.ckpt'
#加载分词器
tokenizer = SpTokenizer(spm_path, token_start=None, token_end='</s>')
keep_tokens = json.load(open(keep_tokens_path))
#加载t5模型
t5 = build_transformer_model(
    config_path=config_path,
    checkpoint_path=fine_tune_checkpoint_path,
    keep_tokens=keep_tokens,
    model='t5.1.1',
    return_keras_model=False,
    name='T5',
)

报错如下：
Traceback (most recent call last):
  File "infer_mt5.py", line 58, in <module>
    name='T5',
  File "/home/finlab/.local/lib/python3.7/site-packages/bert4keras/models.py", line 2443, in build_transformer_model
    transformer.load_weights_from_checkpoint(checkpoint_path)
  File "/home/finlab/.local/lib/python3.7/site-packages/bert4keras/models.py", line 297, in load_weights_from_checkpoint
    raise e
  File "/home/finlab/.local/lib/python3.7/site-packages/bert4keras/models.py", line 291, in load_weights_from_checkpoint
    values.append(self.load_variable(checkpoint, v))
  File "/home/finlab/.local/lib/python3.7/site-packages/bert4keras/models.py", line 1757, in load_variable
    return self.load_embeddings(variable)
  File "/home/finlab/.local/lib/python3.7/site-packages/bert4keras/models.py", line 242, in load_embeddings
    embeddings = embeddings[self.keep_tokens]
IndexError: index 32624 is out of bounds for axis 0 with size 32598

**Comment by yuanshengjun** [comment]
我已经解决了这个bug。
模型加载时，移除keep_tokens。同时在mt5_base_config.json文件修改vocab size。

t5 = build_transformer_model(
config_path=config_path,
checkpoint_path=fine_tune_checkpoint_path,
model='t5.1.1',
return_keras_model=False,
name='T5',
)
